### ISSUE TITLE
Concat with Wildcard *

### ISSUE THREAD

**Issue by gitreich** [nlnwa/warchaeology#141]
I was wondering if it would be possible to allow cat with wildcard:
when there is a folder with some warcs inside a command line usuage like:
 ` warc cat *.warc.gz >> combine_full.warc.gz`
would be ideal

The actual behavior is, that it takes the first warc file performe the cat and does not perform any further operations on the other warc files in the current folder

**Comment by maeb** [comment]
If the records in your WARC files are compressed per record i think you can just use `cat`.

But we will definitely add support for more than one input file. We are quite busy at the moment so please bear with us.

**Comment by gitreich** [comment]
thank you for your very fast response, actually there is no time pressure at all
